# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 880728f3ac08f9d389313f780ec763cfb2c0ea0bfea2902ce304b474616a3d36ee24df291637abb5c0ef8930b571f3e32a9eed19877c1895c66fd58e97aab01e

test:
  secret_key_base: db7e5274ed9d97b4291fe34973f79931cbe02d15564fd0b9eaddd07c6cac7fa025e78e4c5bd9c34dc240e357630fbb6035c9a41c6bbd346fceac83b20166453f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
